### ISSUE TITLE
2 units?

### ISSUE THREAD

**Issue by rimmesbe** [SeanTankGarvey/f1-3-c2p1-colmar-academy#3]
Why are you using px and rem. One is going to overwrite the other. Looks like rem in this case.

https://github.com/SeanTankGarvey/f1-3-c2p1-colmar-academy/blob/master/ColmarAcademy-Capstone/resources/css/style.css#L263-L268

**Comment by SeanTankGarvey** [comment]
Exactly.  I use(d) both because that was the recommendation for anytime you are using rem units while using a base font-size, you are supposed to set a fall-back unit in pixels for browser compatibility.  But you put the pixels first and the rems second so that the rems will override it but if the rems do not read/work, then the pixel value (which should be equivalent) will take effect.

**Comment by SeanTankGarvey** [comment]
There are even post-css scripts like pleeease.io/play/ for people who write in rem units but are too lazy to write the fallback units.  I tend to work the other way around, where I write in pixels first, so/but unfortunately there isn't yet any post-css scripts to convert all my pixel values to rems so I just did that mostly manually and then a few values I looked up with a pixel to rem calculator. Good Observation though.  :-)
